* Merge 1.8.0 manually

diff --git a/release/script/mkdoc b/release/script/mkdoc
--- a/release/script/mkdoc
+++ b/release/script/mkdoc
@@ -1,6 +1,4 @@
-#!/bin/bash
-#
-# $Id: //poco/1.4/release/script/mkdoc#2 $
+#! /bin/sh
 #
 # mkdoc
 #
@@ -14,21 +12,16 @@
 # usage: mkdoc [-l <perforce-label>] [<specfile>]
 #
 
-if [ "$POCO_BASE" = "" ] ; then
-  echo "Error: POCO_BASE not set."
-  exit 1
-fi
-
 osname=`uname -s | tr ' ' '_'`
 osarch=`uname -m | tr ' ' '_'`
 
 if [ ${osname:0:6} = "CYGWIN" ] ; then
-	osname="Cygwin"
+	osname="CYGWIN"
 fi
 
-if [ $osname = "Darwin" ] ; then
-	archpath=`dirname stage/tools/PocoDoc/bin/Darwin/*/PocoDoc`
-	osarch=`basename $archpath`
+if [ "$POCO_BASE" = "" ] ; then
+  echo "Error: POCO_BASE not set."
+  exit 1
 fi
 
 spec=""
@@ -92,17 +85,22 @@ mkrelease -o $tools $version CppParser PocoDoc
 
 cd $tools
 ./configure --no-tests --no-samples --no-prefix
-make -s -j8
+make -s -j8 
 
-if [ $osname = "Cygwin" ] ; then
-    find $tools -type f -name "cyg*$libversion.dll" > $TMP/dlls
+if [ $osname = "CYGWIN" ] ; then
+    find $tools -type f -name "*.$libversion.dll" > $TMP/dlls
     rebase -O -T $TMP/dlls
     rm $TMP/dlls
 fi
 
 cd $POCO_BASE
 
-if [ $osname = "Cygwin" ] ; then
+if [ $osname = "Darwin" ] ; then
+	archpath=`dirname stage/tools/PocoDoc/bin/Darwin/*/PocoDoc`
+	osarch=`basename $archpath`
+fi
+
+if [ $osname = "CYGWIN" ] ; then
 #   Poco dlls must be on PATH for Cygwin
     export PATH=$tools/lib/$osname/$osarch:$PATH
 fi
